export const DATA_DRAFTJS = {
  ROOT: {
    type: { resolvedName: "ContainerElement" },
    isCanvas: true,
    props: {
      flexDirection: "column",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      fillSpace: "no",
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      color: "black",
      shadow: 0,
      radius: 0,
      gap: 10,
      width: "100%",
      height: "auto",
      backgroundColor: "var(--sand-3)",
    },
    displayName: "Container",
    custom: { displayName: "App" },
    hidden: false,
    nodes: ["RnVwNQssxY", "hMR3aAKEFx"],
    linkedNodes: {},
  },
  RnVwNQssxY: {
    type: { resolvedName: "TextComponent" },
    isCanvas: false,
    props: {
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      color: "var(--sand-11)",
      backgroundColor: "transparent",
      shadow: 0,
      text: "It's me again!",
      fontSize: 15,
      textAlign: "left",
      fontWeight: "500",
    },
    displayName: "Text",
    custom: {},
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hMR3aAKEFx: {
    type: { resolvedName: "Novel" },
    isCanvas: false,
    props: {
      paddingLeft: 20,
      paddingRight: 20,
      paddingTop: 10,
      paddingBottom: 10,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      color: "black",
      shadow: 0,
      radius: 0,
      backgroundColor: "transparent",
      content: {
        type: "doc",
        content: [
          {
            type: "heading",
            attrs: { level: 2 },
            content: [{ type: "text", text: "Builderai is awesome" }],
          },
          { type: "paragraph" },
          { type: "paragraph" },
          { type: "paragraph", content: [{ type: "text", text: "dasdadasd" }] },
        ],
      },
    },
    displayName: "My page",
    custom: {},
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
}
