const { fontFamily } = require("tailwindcss/defaultTheme")
const { toRadixVar } = require("windy-radix-palette/vars")

// https://tailwindcss.com/docs/theme#configuration-reference

/** @type {import('tailwindcss').Config} */
module.exports = {
  // mode: "jit", // mode just in time
  darkMode: ["class", '[data-theme="dark"]'],
  // prefix: 'builderai-', // activate to use prefixes here
  content: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}"],
  // disble hover on mobiles
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    screens: {
      sm: "640px", // mobile phones
      md: "768px", // tablets
      lg: "1024px", // desktops
      xl: "1280px", // large screens
      "2xl": "1536px", // extra large screens
    },
    colors: {
      border: toRadixVar("sand", 7),
      input: toRadixVar("sand", 6),
      ring: toRadixVar("sand", 6),
      background: toRadixVar("sand", 3),
      foreground: toRadixVar("sand", 11),
      secondary: {
        DEFAULT: toRadixVar("amber", 9),
        foreground: toRadixVar("sand", 11),
      },
      destructive: {
        DEFAULT: toRadixVar("red", 9),
        foreground: toRadixVar("red", 3),
      },
      muted: {
        DEFAULT: toRadixVar("gray", 7),
        foreground: toRadixVar("gray", 9),
      },
      accent: {
        DEFAULT: toRadixVar("sand", 3),
        foreground: toRadixVar("sand", 11),
      },
      popover: {
        DEFAULT: toRadixVar("sand", 2),
        foreground: toRadixVar("sand", 11),
      },
      card: {
        DEFAULT: toRadixVar("sand", 2),
        foreground: toRadixVar("sand", 11),
      },

      transparent: "transparent",
      current: "currentColor",
      black: "#000",
      white: "#fff",
      gray: {
        DEFAULT: toRadixVar("gray", 1),
        base: toRadixVar("gray", 1),
        bgSubtle: toRadixVar("gray", 2),
        bg: toRadixVar("gray", 3),
        bgHover: toRadixVar("gray", 4),
        bgActive: toRadixVar("gray", 5),
        line: toRadixVar("gray", 6),
        border: toRadixVar("gray", 7),
        borderHover: toRadixVar("gray", 8),
        solid: toRadixVar("gray", 9),
        solidHover: toRadixVar("gray", 10),
        text: toRadixVar("gray", 11),
        textContrast: toRadixVar("gray", 12),
      },
      success: {
        DEFAULT: toRadixVar("green", 1),
        base: toRadixVar("green", 1),
        bgSubtle: toRadixVar("green", 2),
        bg: toRadixVar("green", 3),
        bgHover: toRadixVar("green", 4),
        bgActive: toRadixVar("green", 5),
        line: toRadixVar("green", 6),
        border: toRadixVar("green", 7),
        borderHover: toRadixVar("green", 8),
        solid: toRadixVar("green", 9),
        solidHover: toRadixVar("green", 10),
        text: toRadixVar("green", 11),
        textContrast: toRadixVar("green", 12),
      },
      danger: {
        DEFAULT: toRadixVar("red", 9),
        base: toRadixVar("red", 1),
        bgSubtle: toRadixVar("red", 2),
        bg: toRadixVar("red", 3),
        bgHover: toRadixVar("red", 4),
        bgActive: toRadixVar("red", 5),
        line: toRadixVar("red", 6),
        border: toRadixVar("red", 7),
        borderHover: toRadixVar("red", 8),
        solid: toRadixVar("red", 9),
        solidHover: toRadixVar("red", 10),
        text: toRadixVar("red", 11),
        textContrast: toRadixVar("red", 12),
      },
      warning: {
        DEFAULT: toRadixVar("yellow", 1),
        base: toRadixVar("yellow", 1),
        bgSubtle: toRadixVar("yellow", 2),
        bg: toRadixVar("yellow", 3),
        bgHover: toRadixVar("yellow", 4),
        bgActive: toRadixVar("yellow", 5),
        line: toRadixVar("yellow", 6),
        border: toRadixVar("yellow", 7),
        borderHover: toRadixVar("yellow", 8),
        solid: toRadixVar("yellow", 9),
        solidHover: toRadixVar("yellow", 10),
        text: toRadixVar("yellow", 11),
        textContrast: toRadixVar("yellow", 12),
      },
      info: {
        DEFAULT: toRadixVar("blue", 1),
        base: toRadixVar("blue", 1),
        bgSubtle: toRadixVar("blue", 2),
        bg: toRadixVar("blue", 3),
        bgHover: toRadixVar("blue", 4),
        bgActive: toRadixVar("blue", 5),
        line: toRadixVar("blue", 6),
        border: toRadixVar("blue", 7),
        borderHover: toRadixVar("blue", 8),
        solid: toRadixVar("blue", 9),
        solidHover: toRadixVar("blue", 10),
        text: toRadixVar("blue", 11),
        textContrast: toRadixVar("blue", 12),
      },
      error: {
        DEFAULT: toRadixVar("red", 1),
        base: toRadixVar("red", 1),
        bgSubtle: toRadixVar("red", 2),
        bg: toRadixVar("red", 3),
        bgHover: toRadixVar("red", 4),
        bgActive: toRadixVar("red", 5),
        line: toRadixVar("red", 6),
        border: toRadixVar("red", 7),
        borderHover: toRadixVar("red", 8),
        solid: toRadixVar("red", 9),
        solidHover: toRadixVar("red", 10),
        text: toRadixVar("red", 11),
        textContrast: toRadixVar("red", 12),
      },
      // muted: {
      //   DEFAULT: toRadixVar("gray", 1),
      //   base: toRadixVar("gray", 1),
      //   bgSubtle: toRadixVar("gray", 2),
      //   bg: toRadixVar("gray", 3),
      //   bgHover: toRadixVar("gray", 4),
      //   bgActive: toRadixVar("gray", 5),
      //   line: toRadixVar("gray", 6),
      //   border: toRadixVar("gray", 7),
      //   borderHover: toRadixVar("gray", 8),
      //   solid: toRadixVar("gray", 9),
      //   solidHover: toRadixVar("gray", 10),
      //   text: toRadixVar("gray", 11),
      //   textContrast: toRadixVar("gray", 12),
      // },
      background: {
        DEFAULT: toRadixVar("sand", 1),
        base: toRadixVar("sand", 1),
        bgSubtle: toRadixVar("sand", 2),
        bg: toRadixVar("sand", 3),
        bgHover: toRadixVar("sand", 4),
        bgActive: toRadixVar("sand", 5),
        line: toRadixVar("sand", 6),
        border: toRadixVar("sand", 7),
        borderHover: toRadixVar("sand", 8),
        solid: toRadixVar("sand", 9),
        solidHover: toRadixVar("sand", 10),
        text: toRadixVar("sand", 11),
        textContrast: toRadixVar("sand", 12),
      },
      primary: {
        DEFAULT: toRadixVar("amber", 9),
        foreground: toRadixVar("amber", 12),
        base: toRadixVar("amber", 1),
        bgSubtle: toRadixVar("amber", 2),
        bg: toRadixVar("amber", 3),
        bgHover: toRadixVar("amber", 4),
        bgActive: toRadixVar("amber", 5),
        line: toRadixVar("amber", 6),
        border: toRadixVar("amber", 7),
        borderHover: toRadixVar("amber", 8),
        solid: toRadixVar("amber", 9),
        solidHover: toRadixVar("amber", 10),
        text: toRadixVar("amber", 11),
        textContrast: toRadixVar("amber", 12),
      },
      secondary: {
        DEFAULT: toRadixVar("crimson", 1),
        base: toRadixVar("crimson", 1),
        bgSubtle: toRadixVar("crimson", 2),
        bg: toRadixVar("crimson", 3),
        bgHover: toRadixVar("crimson", 4),
        bgActive: toRadixVar("crimson", 5),
        line: toRadixVar("crimson", 6),
        border: toRadixVar("crimson", 7),
        borderHover: toRadixVar("crimson", 8),
        solid: toRadixVar("crimson", 9),
        solidHover: toRadixVar("crimson", 10),
        text: toRadixVar("crimson", 11),
        textContrast: toRadixVar("crimson", 12),
      },
    },
    borderRadius: {
      lg: "0.5rem",
      md: "calc(0.5rem - 2px)",
      sm: "calc(0.5rem - 4px)",
      full: "9999px",
    },
    borderColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: toRadixVar("sand", 7),
    }),
    // Modify the default ring color so that it matches the brand color:
    ringColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: toRadixVar("sand", 9),
    }),
    ringOffsetColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: toRadixVar("sand", 9),
    }),
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
    },
    letterSpacing: {
      tight: "-0.015em",
    },
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        satoshi: ["var(--font-satoshi)", ...fontFamily.sans],
        inter: ["var(--font-inter)", ...fontFamily.sans],
      },
      // fontSize: {
      //   xs: ["14px", { lineHeight: "24px", letterSpacing: "-0.03em" }],
      // },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  // https://www.youtube.com/watch?v=GEYkwfYytAM&ab_channel=TailwindLabs
  // tpyography is necessary next when we use content
  plugins: [
    require("tailwindcss-animate"),
    require("windy-radix-palette"),
    require("@tailwindcss/typography"),
    require("windy-radix-typography"),
    require("@tailwindcss/line-clamp"),
  ],
}
