export const DEFAULT_STORE = {
  store: {
    "document:document": {
      gridSize: 10,
      name: "",
      meta: {},
      id: "document:document",
      typeName: "document",
    },
    "page:page": {
      meta: {},
      id: "page:page",
      name: "Page 1",
      index: "a1",
      typeName: "page",
    },
    "shape:2uUFfQQPV8W_pYxj0KUgC": {
      x: 165.421875,
      y: 589.79296875,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      type: "arrow",
      parentId: "page:page",
      index: "a1V",
      props: {
        dash: "draw",
        size: "m",
        fill: "none",
        color: "black",
        labelColor: "black",
        bend: 0,
        start: {
          type: "binding",
          boundShapeId: "shape:fZhMWcn8I5WHciny6tuhU",
          normalizedAnchor: { x: 0.5, y: 0.5 },
          isExact: false,
        },
        end: {
          type: "binding",
          boundShapeId: "shape:fZhMWcn8I5WHciny6tuhU",
          normalizedAnchor: { x: 0.5601096487110644, y: 0.9605783274598346 },
          isExact: false,
        },
        arrowheadStart: "none",
        arrowheadEnd: "arrow",
        text: "",
        font: "sans",
      },
      id: "shape:2uUFfQQPV8W_pYxj0KUgC",
      typeName: "shape",
    },
    "shape:Pxv9hWhRVl2yfA2UvPbzb": {
      x: 99.3359375,
      y: 446.66796875,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      type: "text",
      props: {
        color: "black",
        size: "m",
        w: 133.984375,
        text: "asdasdasd",
        font: "draw",
        align: "middle",
        autoSize: true,
        scale: 1,
      },
      parentId: "page:page",
      index: "a3",
      id: "shape:Pxv9hWhRVl2yfA2UvPbzb",
      typeName: "shape",
    },
    "shape:U2zVc4tWHYVVzZKqLll_-": {
      x: 276.6484375,
      y: 629.56640625,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      type: "draw",
      props: {
        segments: [{ type: "free", points: [{ x: 0, y: 0, z: 0.5 }] }],
        color: "black",
        fill: "none",
        dash: "draw",
        size: "m",
        isComplete: true,
        isClosed: false,
        isPen: false,
      },
      parentId: "page:page",
      index: "a2",
      id: "shape:U2zVc4tWHYVVzZKqLll_-",
      typeName: "shape",
    },
    "shape:fZhMWcn8I5WHciny6tuhU": {
      x: 88.125,
      y: 509.85546875,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      type: "geo",
      props: {
        w: 416.1015625,
        h: 291.51953125,
        geo: "rectangle",
        color: "black",
        labelColor: "black",
        fill: "none",
        dash: "draw",
        size: "m",
        font: "draw",
        text: "sdasdasdasd",
        align: "middle",
        verticalAlign: "middle",
        growY: 0,
        url: "",
      },
      parentId: "page:page",
      index: "a1",
      id: "shape:fZhMWcn8I5WHciny6tuhU",
      typeName: "shape",
    },
  },
  schema: {
    schemaVersion: 1,
    storeVersion: 4,
    recordVersions: {
      asset: {
        version: 1,
        subTypeKey: "type",
        subTypeVersions: { image: 2, video: 2, bookmark: 0 },
      },
      camera: { version: 1 },
      document: { version: 2 },
      instance: { version: 22 },
      instance_page_state: { version: 5 },
      page: { version: 1 },
      shape: {
        version: 3,
        subTypeKey: "type",
        subTypeVersions: {
          group: 0,
          text: 1,
          bookmark: 1,
          draw: 1,
          geo: 7,
          note: 4,
          line: 1,
          frame: 0,
          arrow: 1,
          highlight: 0,
          embed: 4,
          image: 2,
          video: 1,
          preview: 0,
        },
      },
      instance_presence: { version: 5 },
      pointer: { version: 1 },
    },
  },
}
