create table "public"."organization" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp without time zone default now(),
    "name" character varying
);


create table "public"."page" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text,
    "description" text,
    "content" json,
    "slug" text,
    "image_url" text,
    "published" boolean default false,
    "org_id" bigint,
    "site_id" bigint
);


create table "public"."profile" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp without time zone default now(),
    "username" character varying,
    "full_name" character varying,
    "avatar_url" character varying,
    "org_id" bigint not null
);


create table "public"."site" (
    "id" bigint generated by default as identity not null,
    "logo" text,
    "name" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp without time zone default now(),
    "custom_domain" text,
    "subdomain" text,
    "org_id" bigint
);


CREATE UNIQUE INDEX organization_pkey ON public.organization USING btree (id);

CREATE UNIQUE INDEX page_pkey ON public.page USING btree (id);

CREATE UNIQUE INDEX profile_id_key ON public.profile USING btree (id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

CREATE UNIQUE INDEX site_pkey ON public.site USING btree (id);

alter table "public"."organization" add constraint "organization_pkey" PRIMARY KEY using index "organization_pkey";

alter table "public"."page" add constraint "page_pkey" PRIMARY KEY using index "page_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."site" add constraint "site_pkey" PRIMARY KEY using index "site_pkey";

alter table "public"."page" add constraint "page_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organization(id) not valid;

alter table "public"."page" validate constraint "page_org_id_fkey";

alter table "public"."page" add constraint "page_site_id_fkey" FOREIGN KEY (site_id) REFERENCES site(id) not valid;

alter table "public"."page" validate constraint "page_site_id_fkey";

alter table "public"."profile" add constraint "profile_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profile" validate constraint "profile_id_fkey";

alter table "public"."profile" add constraint "profile_id_key" UNIQUE using index "profile_id_key";

alter table "public"."profile" add constraint "profile_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organization(id) not valid;

alter table "public"."profile" validate constraint "profile_org_id_fkey";

alter table "public"."site" add constraint "site_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organization(id) not valid;

alter table "public"."site" validate constraint "site_org_id_fkey";


