alter table "public"."profile" drop constraint "profile_org_id_fkey";

alter table "public"."site_users" drop constraint "site_users_org_id_fkey";

alter table "public"."site_users" drop constraint "site_users_site_id_fkey";

alter table "public"."site_users" drop constraint "site_users_user_id_fkey";

alter table "public"."site_users" drop constraint "site_users_pkey";

drop index if exists "public"."site_users_pkey";

drop table "public"."site_users";

create table "public"."organization_profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "role" text default 'member'::text,
    "profile_id" uuid not null,
    "org_id" bigint not null,
    "is_default" boolean default false
);


alter table "public"."profile" drop column "org_id";

CREATE UNIQUE INDEX organization_profiles_pkey ON public.organization_profiles USING btree (profile_id, org_id);

alter table "public"."organization_profiles" add constraint "organization_profiles_pkey" PRIMARY KEY using index "organization_profiles_pkey";

alter table "public"."organization_profiles" add constraint "organization_profiles_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organization(id) not valid;

alter table "public"."organization_profiles" validate constraint "organization_profiles_org_id_fkey";

alter table "public"."organization_profiles" add constraint "organization_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profile(id) not valid;

alter table "public"."organization_profiles" validate constraint "organization_profiles_profile_id_fkey";


