alter table "public"."page" drop constraint "page_site_id_fkey";

alter table "public"."site" drop constraint "site_org_id_fkey";

alter table "public"."site" drop constraint "site_slug_key";

alter table "public"."site" drop constraint "site_pkey";

drop index if exists "public"."site_pkey";

drop index if exists "public"."site_slug_key";

drop table "public"."site";

create table "public"."project" (
    "id" bigint generated by default as identity not null,
    "logo" text,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "custom_domain" text,
    "subdomain" text not null,
    "org_id" bigint,
    "slug" character varying not null default uuid_generate_v4()
);


alter table "public"."page" drop column "site_id";

alter table "public"."page" add column "project_id" bigint;

CREATE UNIQUE INDEX site_pkey ON public.project USING btree (id);

CREATE UNIQUE INDEX site_slug_key ON public.project USING btree (slug);

alter table "public"."project" add constraint "site_pkey" PRIMARY KEY using index "site_pkey";

alter table "public"."page" add constraint "page_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) not valid;

alter table "public"."page" validate constraint "page_project_id_fkey";

alter table "public"."project" add constraint "project_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organization(id) not valid;

alter table "public"."project" validate constraint "project_org_id_fkey";

alter table "public"."project" add constraint "site_slug_key" UNIQUE using index "site_slug_key";


