#!/usr/bin/env bash

set -o errexit  # always exit on error
set -o errtrace # trap errors in functions as well
set -o pipefail # don't ignore exit codes when piping output
set -o posix    # more strict failures in subshells

echo "Running pre-commit hook"

# Activate virtual environment
source internal/tinybird/.venv/bin/activate

pnpm lint-staged
pnpm test

# Deactivate virtual environment
deactivate
