#!/usr/bin/env bash

set -o errexit  # always exit on error
set -o errtrace # trap errors in functions as well
set -o pipefail # don't ignore exit codes when piping output
set -o posix    # more strict failures in subshells

echo "Running pre-commit hook"

pnpm lint-staged
pnpm typecheck
pnpm test

echo "Checking tinybird deployment"
cd internal/analytics
TB_VERSION_WARNING=0 tb build
cd ../../

echo "Pre-commit hook completed"
