
name: Tinybird - CI Workflow

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/analytics
    services:
      tinybird:
        image: tinybirdco/tinybird-local:beta
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v5

      - name: Install Tinybird CLI
        run: curl https://tinybird.co | sh

      - name: Build project
        run: tb build

      - name: Test project
        run: tb test run
